// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6auszEcjBEJ7hw8E5XUEY9U_qqVVQIM',
    appId: '1:1076877856118:web:57a845b3328f29b238be57',
    messagingSenderId: '1076877856118',
    projectId: 'providerapp-736',
    authDomain: 'providerapp-736.firebaseapp.com',
    storageBucket: 'providerapp-736.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2234Jrjg1l1nCBn6-l2oTrrQGDFagE_E',
    appId: '1:1076877856118:android:49dcfd3421db936a38be57',
    messagingSenderId: '1076877856118',
    projectId: 'providerapp-736',
    storageBucket: 'providerapp-736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiP6nDCnKezCLSW0NFeyPle4HjdAhIJEU',
    appId: '1:1076877856118:ios:73e25c9a7f4ce01d38be57',
    messagingSenderId: '1076877856118',
    projectId: 'providerapp-736',
    storageBucket: 'providerapp-736.appspot.com',
    iosBundleId: 'cm.codingmindstemplate',
  );
}
